apiVersion: apps/v1
kind: Deployment
metadata:
  name: eta-deploy
  labels:
    app: eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eta-app
  template:
    metadata:
      labels:
        app: eta-app
    spec:
      containers:
      - name: eta-container
        image: ashoke0804/devops_repo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eta-np-service
  labels:
    app: eta-app
spec:
  selector:
    app: eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
